### PR TITLE
Adding a way to define additional options

### PR DESCRIPTION
**Pull request by SeleniumTestAB**
## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

The user will be able to define his/her additional options without need to create additional class that implements WebDriverProvider interface. This could result in less complex code and more verbose way of defing settings by the user.

This feature supports Chrome, Firefox and Opera browser because rest of the browser still use Capabilities instead of options.

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome_headless firefox_headless` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by BorisOsipov** [comment]
There is already way how to pass any additional options to driver factories. It is `Configuration.browserCapabilities`. We dont need some new way to do it only for options.

**Comment by SeleniumTestAB** [comment]
@BorisOsipov Capabilities itself are deprecated so its better to set those via options not to mention that only real reason to make WebDriverProvider is to set those options when you just simply could add them via Configuration property.

**Comment by BorisOsipov** [comment]
>Capabilities itself are deprecated

Nope.
See docs - https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/remote/DesiredCapabilities.html

> its better to set those via options not to mention that only real reason to make WebDriverProvider is to set those options when you just simply could add them via Configuration property.

Once again you can do the same by `Configuration.browserCapabilities` and it will work for all browsers not only for chrome\ff\opera.

We definitely will get rid of capabilities, when driver constructors will completely remove [this api](https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/chrome/ChromeDriver.html#ChromeDriver-org.openqa.selenium.Capabilities-).

Now I don't understand why we have to create two ways to do the same and confuse people how combinations of this will work.

**Comment by BorisOsipov** [comment]
@SeleniumTestAB I understand your conserns. Let's continue conversation in https://github.com/selenide/selenide/issues/1097

**Pull request closed without merging**
