### PR TITLE
Add method `SelenideLogger.step`

### PR DESCRIPTION
**Pull request by Au6ojlut**
## Proposed changes
Add feature requested in https://github.com/selenide/selenide/issues/2172

## Checklist
- [x] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [?] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by asolntsev — APPROVED** [review]

**Comment by asolntsev** [comment]
@Au6ojlut Hi. Thank you for the contribution. 

Did you also write some integration test?

For example, I am trying to run such a test with few inner steps:
```java
@ExtendWith(TextReportExtension.class)
public class StepsTest {
  @Test
  void canUseInnerSteps() {
    step("login", () -> {
      step("open login page", () -> {
        open("https://the-internet.herokuapp.com/login");
        return null;
      });

      step("failed login", () -> {
        $("#username").val("tomsmith");
        $("#password").val("wrong");
        return null;
      });

      step("successful login", () -> {
        $("#username").val("tomsmith");
        $("#password").val("SuperSecretPassword!");
        return null;
      });
      return null;
    });
  }
}
```

But I am getting a strange report where _step name_ (e.g. "failed login") if showed **after** the step actions:
```
+----------------------+------------------------------------------+------------+------------+
| Element              | Subject                                  | Status     | ms.        |
+----------------------+------------------------------------------+------------+------------+
| webdriver            | create()                                 | PASS       | 1009       |
|   open               | https://the-internet.herokuapp.com/login | PASS       | 2746       |
|     open login page  |                                          | PASS       | 2770       |
| #username            | val(tomsmith)                            | PASS       | 126        |
| #password            | val(wrong)                               | PASS       | 112        |
|   failed login       |                                          | PASS       | 259        |
| #username            | val(tomsmith)                            | PASS       | 43         |
| #password            | val(SuperSecretPassword!)                | PASS       | 47         |
|   successful login   |                                          | PASS       | 90         |
|     login            |                                          | PASS       | 3121       |
+----------------------+------------------------------------------+------------+------------+
```

**Comment by Au6ojlut** [comment]
Sorry, I didn't test it with integration tests.

Will fix it soon

**Comment by Au6ojlut** [comment]
The problem was with the sort order. I didn't check it before `generateReport` call.

It could be fixed, by changing `EventCollector`'s logic: store event on `beforeEvent` and ignore on `afterEvent` call.
But, I believe, that sorting events before `generateReport` call is more robust solution.

**Review by asolntsev — APPROVED** [review]

**Comment by asolntsev** [comment]
@Au6ojlut Thanks! There is two failing tests, unfortunately...

**Comment by Au6ojlut** [comment]
My bad =(

Fixed

**Comment by asolntsev** [comment]
@Au6ojlut Thank you! Merged. Will be released in Selenide 6.14.0

**Pull request merged**
