### PR TITLE
add a fatJar task

### PR DESCRIPTION
**Pull request by jpratt2**
Adding a fatJar task will enable some contributors to test pre-release builds using typical syntax such as "open"

### CODE REVIEW

**Comment by asolntsev** [comment]
@jpratt2 We can build fat jar, no problems. 
But let me ask how it helps contributors to test pre-release builds? 
Don't you just use SNAPSHOT version?

**Comment by jpratt2** [comment]
I don't know how to test using "open" and get all of the dependencies. Is there a better way, using Selenide 5.11

**Comment by asolntsev** [comment]
@jpratt2 Sure. Read about SNAPSHOTS. 

Shortly said, while the version is under development, it ends with "snapshot". Currently Selenide version in master branch is `5.11.0-SNAPSHOT`. 

When you modify the source locally, you just call `./gradlew install`. You will see a new file `~/.m2/repository/com/codeborne/selenide/5.11.0-SNAPSHOT/selenide-5.11.0-SNAPSHOT.jar`. Now you can add a dependency `com.codeborne:selenide:5.11.0-SNAPSHOT` in any other project and run it on your machine.

**Comment by jpratt2** [comment]
Ah, I needed a pre-release because I added a dependency.
OK, it's up to you if you think other contributors may benefit or not. Thank you for explaining.

**Comment by asolntsev** [comment]
@jpratt2 Yes, that's why SNAPSHOTs are needed. You declare `com.codeborne:selenide:5.11.0-SNAPSHOT` dependency and get it with all its transitive dependencies, as any other gradle/maven artifact.

**Comment by jpratt2** [comment]
OK, thank you for help. Closing pull request.

**Pull request closed without merging**
