### PR TITLE
#201 can click elements with zero opacity

### PR DESCRIPTION
**Pull request by asolntsev**
This is a possible solution for https://github.com/selenide/selenide/issues/201

## Proposed changes
Change method `$.click()` so that it doesn't require element to be visible.

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome htmlunit` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by asolntsev** [comment]
@rosolko yes, that's why I am in doubt. Test definitely should not click hidden elements. But in this case the element is visible (even with `opacity: 0`). This is some css magic.

**Comment by BorisOsipov** [comment]
I let myself introduce more ugly, but more safe solution: add a new click method that will work with invisible elements. E.g. `$().superclick`
Pros:
- more safe solution - users that don't run into issue with css magic will not be able to shout in his legs when they will click to invisible element by mistake in locator(for me it is most common case when visibilty check safes our nerve cells).
- it is clear in the code that is edge case

Cons:
- new method and additional effort to support
- ugly method name

**Comment by rosolko** [comment]
@BorisOsipov @asolntsev 
If add some new method I think it would be better to give more obvious name, something like `clickIgnoreVisibility` for example.

**Comment by BorisOsipov** [comment]
>If add some new method I think it would be better to give more obvious name,

@rosolko Sure. I've called it `superclick` just for example

**Comment by asolntsev** [comment]
@rosolko @BorisOsipov @gedankennebel @zolrath I like it, but name seems to be invalid. There should not be two verbs in a method name. Probably
* `clickIgnoringVisibility()`
* `click(false)`
* `forcedClick()`
* `mayTheForceBeWithClick()`
* `clickThrough()`

more ideas?

**Comment by BorisOsipov** [comment]
@asolntsev does the new method name fit you? It will be nice to merge this.

**Comment by symonk** [comment]
LGTM

**Comment by vinogradoff** [comment]
I am against adding a method for an action a user cannot do himself in browser

**Comment by jkromski** [comment]
I created test for no-size element click in pr below please take a look and merge it with click-hidden-elements if it ok with you
https://github.com/selenide/selenide/pull/879

**Comment by rosolko** [comment]
implemented in #874

**Pull request closed without merging**
