### PR TITLE
add setDriver method to WebDriverRunner

### PR DESCRIPTION
**Pull request by PetroOv**
## Proposed changes
Selenide already has methods to create a new browser on demand, but it doesn't allow us to change their configuration or we could create our own WebDriver, but in this case, additional selenide functionality wouldn't be applied. So, I introduced a method that creates a new browser but is fully controlled by selenide (listeners, deadwatch etc).

## Checklist
- [ ] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by BorisOsipov — CHANGES_REQUESTED** [review]
We have already discussed this [here](https://github.com/selenide/selenide/issues/1372), and it is a good api decision to allow users to create new drivers with config via the `Selenide.open(config)` api.

`WebDriverRunner.setDriver(config);` api looks confused. It looks like a setter, but it does different work.

**Comment by PetroOv** [comment]
> We have already discussed this [here](https://github.com/selenide/selenide/issues/1372), and it is a good api decision to allow users to create new drivers with config via the `Selenide.open(config)` api.
> 
> `WebDriverRunner.setDriver(config);` api looks confused. It looks like a setter, but it does different work.

Ok, could it be like 2 methods in Selenide class.
Selenide#open(java.lang.String, com.codeborne.selenide.Config) 
Selenide#open(com.codeborne.selenide.Config) 

And WebDriverRunner method rename from setDriver() to replaceBrowser()
What do u think, does it sound good?

**Comment by BorisOsipov** [comment]
>Ok, could it be like 2 methods in Selenide class.
>Selenide#open(java.lang.String, com.codeborne.selenide.Config)
>Selenide#open(com.codeborne.selenide.Config)

It seems good for first iteration.

>And WebDriverRunner method rename from setDriver() to replaceBrowser()
>What do u think, does it sound good?

There are at least two cases:
1) You want to create a driver with a specific configuration, but you don't want to mutate the global `Configuration' object.
2) You want to close the current driver and start a new one with a specific configuration, but you don't want to mutate the global `Configuration` object.

Question 1:

Should `Selenide#open(com.codeborne.selenide.Config)` close the current driver if it already exists?

For case 2 it is obvious yes. For case 1 it is not clear. 

From my point of view, it must not touch the previous driver.
1) As a user I don't expect `Selenide#open(com.codeborne.selenide.Config)` to close the previous one. I may have references to driver outside selenide for some reason and may want to work with them.
2) `com.codeborne.selenide.WebDriverRunner#setWebDriver(org.openqa.selenium.WebDriver)` does not close the previous one and silently change the current driver to provided.
3) It is not a problem at all to call `closeWebdriver()` if  you need and then call `open(config)`. 

Are there any insights you may have that I could miss for closing previous drivers?

**Comment by PetroOv** [comment]
> > Ok, could it be like 2 methods in Selenide class.
> > Selenide#open(java.lang.String, com.codeborne.selenide.Config)
> > Selenide#open(com.codeborne.selenide.Config)
> 
> It seems good for first iteration.
> 
> > And WebDriverRunner method rename from setDriver() to replaceBrowser()
> > What do u think, does it sound good?
> 
> There are at least two cases:
> 
> 1. You want to create a driver with a specific configuration, but you don't want to mutate the global `Configuration' object.
> 2. You want to close the current driver and start a new one with a specific configuration, but you don't want to mutate the global `Configuration` object.
> 
> Question 1:
> 
> Should `Selenide#open(com.codeborne.selenide.Config)` close the current driver if it already exists?
> 
> For case 2 it is obvious yes. For case 1 it is not clear.
> 
> From my point of view, it must not touch the previous driver.
> 
> 1. As a user I don't expect `Selenide#open(com.codeborne.selenide.Config)` to close the previous one. I may have references to driver outside selenide for some reason and may want to work with them.
> 2. `com.codeborne.selenide.WebDriverRunner#setWebDriver(org.openqa.selenium.WebDriver)` does not close the previous one and silently change the current driver to provided.
> 3. It is not a problem at all to call `closeWebdriver()` if  you need and then call `open(config)`.
> 
> Are there any insights you may have that I could miss for closing previous drivers?

You are right, new open(Config) method should be aligned with the existing ones
So, we need to use the old browser if possible. As a solution, I decided to add newBrowser method which is similar to InNewBrowser. The only thing that bothers me, now we have cases where config would be ignored.

**Pull request closed without merging**
