### PR TITLE
Ignore escaping commas

### PR DESCRIPTION
**Pull request by FrameBassman**
## Proposed changes
Fix for https://github.com/codeborne/selenide/issues/697 

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome htmlunit` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by FrameBassman** [comment]
I think that current suggested solution in issue is not effective due to complex string processing. 
I suggest to escape all important commas in arguments via backslash () character.

**Comment by BorisOsipov** [comment]
@vinogradoff can you look into this and give our feedback?

**Comment by vinogradoff** [comment]
Hm, I think \\, is not intuitive, and only can be used if documented well.

Is Quotes processing really that complex?

**Comment by vinogradoff** [comment]
Propose to close - solved in #883

**Comment by asolntsev** [comment]
@vinogradoff Can you resolve conflicts?

**Comment by vinogradoff** [comment]
Solved with #883

**Pull request closed without merging**
