### PR TITLE
Feature: set active SelenideDriver

### PR DESCRIPTION
**Pull request by sanchek**
https://github.com/selenide/selenide/issues/1296

### CODE REVIEW

**Comment by Tonicku** [comment]
Hi, i am interested about this feature and looking forward to use it 👍

**Comment by asolntsev** [comment]
@Tonicku Could you please describe the context: why do you need this feature? I still think it should not be needed.

**Comment by Tonicku** [comment]
> @Tonicku Could you please describe the context: why do you need this feature? I still think it should not be needed.

Hi Andrei, yeaaa i somehow sort out what i want to achieve.

Selenide 
- Configuration is not ThreadLocal
- WebDriver is theadlocal inside WebDriverRunner

Challenge
- setup selenide.configuration for specific tests set : PageLoadStrategy, hub url, browser, environment, local vs remote, 

Solution i put in place

TESTNG XML
- as i am using Testng xml to group the test by their configuration ( eager, normal )
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Test Suite" verbose="10" parallel="classes" thread-count="1" time-out="11080000">

    <parameter name="TYPE" value="local"/>
    <parameter name="HUB" value="http://mgs-qa-k8s-harbor201.be.monster.com:32444/wd/hub"/>
    <parameter name="ENV" value="TEST_ENV"/>

    <test name=" tests PageLoadStrategy EAGER">

        <parameter name="PAGE_LOAD_STRATEGY" value="eager"/>
       <parameter name="BROWSER" value="chrome"/>

        <packages>
            <package name="${path/package/*}"/>
        </packages>

    </test>

    <test name=" tests PageLoadStrategy NORMAL">

        <parameter name="PAGE_LOAD_STRATEGY" value="normal"/>
       <parameter name="BROWSER" value="chrome"/>

        <packages>
            <package name="${path/package/*}"/>
        </packages>

    </test>

    <test name=" tests PageLoadStrategy NORMAL">

        <parameter name="PAGE_LOAD_STRATEGY" value="normal"/>
       <parameter name="BROWSER" value="edge"/>

        <packages>
            <package name="${path/package/*}"/>
        </packages>

    </test>

</suite>

UITestBase
usage of the @Test testng annotation
reusing the parameters from the testng xml, to set the configuration for these test sets

Let me know if it 's accurate solution

**Comment by asolntsev** [comment]
> * setup selenide.configuration for specific tests set : PageLoadStrategy, hub url, browser, environment, local vs remote,

Hi @Tonicku !
Why do you need to use different PageLoadStrategies or hubs in parallel tests?
I don't think it's really needed.

I think a better idea is to create different profiles (in Maven) or tasks (in Gradle) or test suites (in TestNG).
See for example https://github.com/selenide-examples/google/blob/master/pom.xml

**Comment by Tonicku** [comment]
@asolntsev Thanks for your reply. we have few tests with images to be tested and without few. When we know they are no images to check : we want PageLoadStrategies to be set to eager, if not normal.
Thanks for sharing how to put in place the usage of Profile.

**Pull request closed without merging**
