### PR TITLE
Add selenide's create driver log

### PR DESCRIPTION
**Pull request by petroOv-PDFfiller**
## Proposed changes
In Selenide report is impossible to get information when the browser was created(or recreated) and how much time the test spend on this action. I think that it can be useful as other logs, generated by Selenide. 
log example: 
image

## Checklist
- [x] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by petroOv-PDFfiller** [comment]
or better use webdriver : create() - similar to close event( webdriver: close() )?

**Comment by petroOv-PDFfiller** [comment]
@asolntsev is everything ok with firefox tests on linux? I tried to reproduce fails locally but was unsuccessful. all tests are green

**Comment by asolntsev** [comment]
> @asolntsev is everything ok with firefox tests on linux? I tried to reproduce fails locally but was unsuccessful. all tests are green

Yes, quite often Firefox fails to start in GitHub actions. I don't know yet how to fix it. :(

**Comment by petroOv-PDFfiller** [comment]
> > @asolntsev is everything ok with firefox tests on linux? I tried to reproduce fails locally but was unsuccessful. all tests are green
> 
> Yes, quite often Firefox fails to start in GitHub actions. I don't know yet how to fix it. :(

Oh, it's sad, looks like a hard task to debug( Could I leave a pull request with these fails? And if you have some free time, could you review it?

**Comment by asolntsev** [comment]
Sure, it's fine. Will review it soon.

**Review by asolntsev — APPROVED** [review]

**Pull request merged**
