### PR TITLE
#766 selected text condition @WIP

### PR DESCRIPTION
**Pull request by symonk**
## Proposed changes
Provides capabilities for selenide to read and assert against the 'selected' or 'highlighted' text of a given input field as requested in #766.

By 'highlighted' or 'selected' we mean => The text on the element that if a user was to issue a copy command, would be copied to the clipboard.

Would like some feedback on this as an approach to this feature, this PR is a work in progress.  Example output where the selected text is not matching:

```
Element should have selectedText 't2his ' {By.id: selected}
Element: '<input id="selected" type="text" value="this is a long piece of selectable text"></input>'
Actual value: 'this '
```

Thoughts? thanks for your time.

## Checklist
- [X] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome htmlunit` command
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by symonk** [comment]
I think WDM decided to give up on travis :(

**Comment by rosolko** [comment]
@asolntsev @BorisOsipov In my opinion it's also should be move to community conditions tab.

**Comment by rosolko** [comment]
@symonk create block on community condition because it's not common specific case

**Comment by rosolko** [comment]
@symonk any progress?

**Comment by asolntsev** [comment]
@symonk Thank you for the pull request. Merged!

Sorry for the delay.

**Pull request merged**
