### PR TITLE
updated webdrivermanager to 4.4.1

### PR DESCRIPTION
**Pull request by anilreddy**
updated webdrivermanager to 4.4.1

## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Checklist
- [x] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by BorisOsipov — APPROVED** [review]

**Comment by BorisOsipov** [comment]
thanks @anilreddy.

do you need a new Selenide release with WDM update?

**Comment by anilreddy** [comment]
Yeah it would be better as it is an hotfix in the WDM

**Comment by asolntsev** [comment]
@anilreddy  ok, hold my beer....

**Comment by asolntsev** [comment]
@anilreddy @BorisOsipov Catch up Selenide 5.20.4 after a few minutes...

**Pull request merged**
