### PR TITLE
Add support for Chrome option "useAutomationExtension"

### PR DESCRIPTION
**Pull request by harshtuna**
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1749#c5

## Proposed changes
Configure useAutomationExtension using system property - same as args and prefs

## Checklist
- [ ] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome htmlunit` command
> Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: config/checkstyle/suppressions.xml
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by BorisOsipov** [comment]
Hi @harshtuna 

If we follow such approach(add sys env for each experimentalOption name) at the end we will have thousands of them - it is bad.

**Comment by harshtuna** [comment]
> Hi @harshtuna
> 
> If we follow such approach(add sys env for each experimentalOption name) at the end we will have thousands of them - it is bad.

What are the options then? Maybe allow injecting partly configured webdriver instance and merge selenide configuration on top? Not using selenide factory for complex setup and use selenide api directly is another choice.

**Comment by BorisOsipov** [comment]
>Maybe allow injecting partly configured webdriver instance and merge selenide configuration on top?

It isn't possible. Once driver was created there is no ability to change e.g. capabilities.

Did you consider using `WebDriverProvider` in your project? See https://github.com/selenide/selenide/wiki/How-Selenide-creates-WebDriver

**Comment by harshtuna** [comment]
> > Maybe allow injecting partly configured webdriver instance and merge selenide configuration on top?
> 
> It isn't possible. Once driver was created there is no ability to change e.g. capabilities.
> 
> Did you consider using `WebDriverProvider` in your project? See https://github.com/selenide/selenide/wiki/How-Selenide-creates-WebDriver

Yes, that was our plan B. Rejecting the PR then.

**Pull request closed without merging**
