### PR TITLE
Appium: added tap, doubleTap commands

### PR DESCRIPTION
**Pull request by qwez**
## Proposed changes
Using of `SelenideAppiumElement.click(tap())` is kinda annoying, so `tap()` and `doubleTap()` commands are introduced

## Checklist
- [x] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by amuthansakthivel** [comment]
It is better to add an integration test instead of a mock test. You can reuse the test that already written on AndroidClickOptionsTest and IosClickOptionsTest

**Comment by qwez** [comment]
> It is better to add an integration test instead of a mock test. You can reuse the test that already written on AndroidClickOptionsTest and IosClickOptionsTest

Ok. Should I delete my mock tests, or let them be.

**Comment by asolntsev** [comment]
@qwez You can leave your unit-tests if you wish (though, I don't see a big value in it after adding integration tests).

**Review by asolntsev — APPROVED** [review]
Thumbs up!

**Comment by amuthansakthivel** [comment]
@qwez - can you update the README.md with this information

**Pull request merged**
