### PR TITLE
#1338 improve message of waitUntil/waitWhile methods

### PR DESCRIPTION
**Pull request by asolntsev**
fix for https://github.com/selenide/selenide/issues/1338

### CODE REVIEW

**Comment by rosolko** [comment]
Since check methods accept `Duration` can you please also add tests with different `Duration` types?

**Review by rosolko — COMMENTED** [review]
@asolntsev, since check methods accept Duration can you please also add tests with different Duration types?

**Comment by asolntsev** [comment]
@rosolko tests added

**Review by rosolko — APPROVED** [review]
looks good

**Review by dstekanov — APPROVED** [review]
That's great!

**Pull request merged**
