### PR TITLE
Fixing inconsistency with transparent elements

### PR DESCRIPTION
**Pull request by vinogradoff**
fix for #201. Now Selenide can interact with element that have opacity:0 the same way as browser users can.

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome htmlunit` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by BorisOsipov** [comment]
I have to mention one disadvantage for this approach - it requires one more request to browser on each interaction. So we will decrease perfomance for end users.

**Comment by vinogradoff** [comment]
Very good point. Actually it should only do the second call if visible is
false - which is okay. If Condition.or doesn't evaluate further conditions
after any conditions evaluates true. Could you please check or method?
Viele Grüße

Alexei Vinogradov

**Comment by BorisOsipov** [comment]
>If Condition.or doesn't evaluate further conditions
after any conditions evaluates true. Could you please check or method?
Yep It works as expected.

**Comment by vinogradoff** [comment]
Thanks! Then the fix makes not  slower as it is now, because now it makes 2
checks only when original version would fail the test.

The next step would be try to drop the both checks and just do click
relying on underlying Selenium behavior (though catching and wrapping
exceptions for readable diagnostics).

But I see it as separate piece of work. Do you agree?


Viele Grüße

Alexei Vinogradov

**Comment by vinogradoff** [comment]
Lets put discussion to new issue?
I'll create it.

Is the fix okay for now in your opinion?)

Viele Grüße

Alexei Vinogradov

**Comment by jkromski** [comment]
can you this test too please
https://github.com/selenide/selenide/pull/881

**Pull request merged**
