### PR TITLE
 Implemented drag and drop by JS  (issue 1110)

### PR DESCRIPTION
**Pull request by dbudim**
## Proposed changes
Implemented [issue 1110](https://github.com/selenide/selenide/issues/1110)
Tested both on chrome and firefox, works fine

## Checklist
- [x] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by asolntsev — CHANGES_REQUESTED** [review]
@dbudim Thank you for the PR! People do need a working Drag'n'Drop. :)

1. Current implementation only works on pages with JQuery. But nowdays JQuery is not so popular anymore. Can't we rewrite the JS code to work without JQuery? Probably http://youmightnotneedjquery.com/ can help.
2. Instead of having two methods `$.dragAndDrop()` and `$.dragAndDropByJs()`, it's probably better to have one method `$.dragAndDrop()` with parameters.

Then it would look like `$.dragAndDrop(usingJavaScript())`. See for example similar api for clicks: https://ru.selenide.org/2020/09/26/selenide-5.15.0/

**Comment by dbudim** [comment]
> @dbudim Thank you for the PR! People do need a working Drag'n'Drop. :)
> 
> 1. Current implementation only works on pages with JQuery. But nowdays JQuery is not so popular anymore. Can't we rewrite the JS code to work without JQuery? Probably http://youmightnotneedjquery.com/ can help.
> 2. Instead of having two methods `$.dragAndDrop()` and `$.dragAndDropByJs()`, it's probably better to have one method `$.dragAndDrop()` with parameters.
> 
> Then it would look like `$.dragAndDrop(usingJavaScript())`. See for example similar api for clicks: https://ru.selenide.org/2020/09/26/selenide-5.15.0/

@asolntsev done)
I found implementation on JS and used it, works fine)
Also moved solution to existed drag and drop command. 
As for drag function there are no many arguments as for ClickOptions, i've just added overloaded version with boolean param:
`dragAndDropTo(String targetCssSelector, boolean useJavaScript);`

So we have regular`$("#drag1").dragAndDropTo("#div2");` and JS `$("#drag1").dragAndDropTo("#div2", true);`

If it's ok, all is done, if need to make same as ClickOptions please tell, i'll do)

**Comment by BorisOsipov** [comment]
>i've just added overloaded version with boolean param

it isn't smell good. I think `FooBarOptions` will be better.

**Comment by dbudim** [comment]
> > i've just added overloaded version with boolean param
> 
> it isn't smell good. I think `FooBarOptions` will be better.

@BorisOsipov I've made this because i don't imagine what other options could be added to DragAndDrop command. So i thought that creating DragAndDropOptions for only one option is not needed) But if need make it for consistency with other commands I'll make it)

Should i move from boolean param to DragAndDropOptions ?)

**Comment by asolntsev** [comment]
@dbudim I can imagine quite many options: speed of moving the cursor, pause before, pause after, shift from the center of the element etc.

**Comment by dbudim** [comment]
> @dbudim I can imagine quite many options: speed of moving the cursor, pause before, pause after, shift from the center of the element etc.


> @dbudim I can imagine quite many options: speed of moving the cursor, pause before, pause after, shift from the center of the element etc.

@asolntsev 
Wow it's a great field for customisation) For me there was sufficient standart implementation )

Done)
Added `dragAndDropTo(String targetCssSelector, DragAndDropOptions options);`

**Review by asolntsev — APPROVED** [review]

**Comment by asolntsev** [comment]
@dbudim Wow, it's pure JS and it works in all browsers! Bravo!

**Comment by asolntsev** [comment]
@dbudim I think I will even enable JS mode by default. Because "actions" mode doesn't really work in any browsers.

**Comment by dbudim** [comment]
> @dbudim I think I will even enable JS mode by default. Because "actions" mode doesn't really work in any browsers. 

Great)
Also I checked logs, even with spending time for reading js from file it works faster than regular actions)

**Comment by vprystash** [comment]
Hi, when it will be possible to use this feature?

**Comment by asolntsev** [comment]
I am going to release Selenide 5.19.0 soon. Tonight or tomorrow.

**Comment by vprystash** [comment]
Sorry for disturbing you, but I really need this feature about drag&drop, when will it be possible to update?

**Comment by rosolko** [comment]
> Tonight or tomorrow.

**Comment by asolntsev** [comment]
@vprystash Well, will release it today. For sure. :)

**Pull request merged**
