### PR TITLE
Ensure that tests formatting numbers work in all machines regarding their user language

### PR DESCRIPTION
**Pull request by cocorossello**
I did a gradlew check in my machine to see if I could help somewhere and some tests were failing due to different number format expected (spanish). Example: 

`expected: "180.300 s."
but was : "180,300 s."
org.opentest4j.AssertionFailedError: 
expected: "180.300 s."
but was : "180,300 s."
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at com.codeborne.selenide.impl.DurationFormatTest.greaterThanMinute(DurationFormatTest.java:40)`

So this is a tiny PR to avoid this little pitfall.

## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Checklist
- [X ] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by asolntsev** [comment]
@cocorossello Thank you for the PR. 
Let's discuss what options we have.

I see a problem with it: when somebody runs tests in IDE instead of Gradle, he will get the same problem (failing `DurationFormatTest` and `SelenideLoggerTest`). 

What do you think about using a little bit different approach?
1. Create a `@Rule` that sets a `Locale.setDefault(ENGLISH);` explicitly before `DurationFormatTest` and `SelenideLoggerTest` (and restores after the test).
2. To be sure that default locale is not occasionally used in some other tests, we add a line `systemProperty('user.language', 'fr')` to `tests.gradle`

**Comment by cocorossello** [comment]
Didn't see that test.gradle. I'm fine with your approach, let me update the PR

**Review by asolntsev — CHANGES_REQUESTED** [review]
Everything is good except one minor thing: we need to use 2 annotations (`@ExtendWith` and `@UseLocale`).

To avoid need for `@UseLocale` annotation, we could declare `UseLocaleExtension` a bit differently:

```
@RegisterExtension static UseLocaleExtenstion useLocale = new UseLocaleExtenstion("en");
```

**Comment by cocorossello** [comment]
Yes, much better, didn't know about that.

**Review by asolntsev — APPROVED** [review]

**Comment by asolntsev** [comment]
@cocorossello Than you for your work! Merged and will be released soon.

**Pull request merged**
