### PR TITLE
Selenide#2050: Improve syntax

### PR DESCRIPTION
**Pull request by cocorossello**
Just improve syntax a little bit with some functional style

I made something very stupid with rebase, I'm not used to doing this, so I started over in another PR.

If you want to keep IE11 compatibility just close the PR.

## Checklist
- [X] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by asolntsev — APPROVED** [review]
This code doesn't work in IE, 
but
it's not a problem because the previous code did work either.

We have an open issue anyway, and will solve it at once in all JS code: https://github.com/selenide/selenide/issues/2042

**Comment by asolntsev** [comment]
@cocorossello I would like to merge this PR, but it has merge conflicts. Could you resolve them? Probably just rebase the branch from master.

**Comment by cocorossello** [comment]
I have opened #2080. I'm closing this one. Sorry for the inconveniences

**Comment by asolntsev** [comment]
overseded by https://github.com/selenide/selenide/pull/2080

**Pull request closed without merging**
