### PR TITLE
#1008 add support for system property "chromeoptions.mobileEmulation"

### PR DESCRIPTION
**Pull request by asolntsev**
Still, I am not sure it's a good idea.
Making this PR to show the idea how to achieve the goal with just 3 lines of code. :)

### CODE REVIEW

**Comment by vinogradoff** [comment]
I like it.

**Comment by osyanin** [comment]
Billion likes!

**Comment by vinogradoff** [comment]
why not

**Comment by dstoianov** [comment]
the test is really weird

**Comment by asolntsev** [comment]
@dstoianov What you mean? Why it's bad to close any previously opened browser?

**Comment by dstoianov** [comment]
The feature is ok, but the method close in beforEach looks a bit strange

**Comment by asolntsev** [comment]
@fabb Basically your question is the same as https://github.com/selenide/selenide/issues/1372. 
Answer: no, it's not implemented yet.

But you can do it if you open webdriver by yourself in your code.

**Pull request merged**
