### PR TITLE
Copy/Paste tests for PR #2027

### PR DESCRIPTION
**Pull request by evpl**
Tests for PR #2027

### CODE REVIEW

**Comment by asolntsev** [comment]
@evpl Unfortunately, clipboard doesn't work in non-graphics environment:

```java
CopyPasteTest > copyEmptySelection() FAILED
    java.awt.HeadlessException: 
    No X11 DISPLAY variable was set,
    but this program performed an operation which requires it.
        at java.desktop/sun.awt.HeadlessToolkit.getSystemClipboard(HeadlessToolkit.java:216)
        at com.codeborne.selenide.DefaultClipboard.setText(DefaultClipboard.java:50)
        at integration.CopyPasteTest.copyEmptySelection(CopyPasteTest.java:16)
```

So we have to disable these tests on github actions, see
https://github.com/selenide/selenide/blob/master/statics/src/test/java/integration/DefaultClipboardTest.java

**Comment by evpl** [comment]
@asolntsev Done

**Review by asolntsev — APPROVED** [review]

**Comment by asolntsev** [comment]
@evpl thanks, merged.

**Comment by asolntsev** [comment]
@evpl still, some of these tests failed. :(
See PR https://github.com/selenide/selenide/pull/2114

**Pull request merged**
