### PR TITLE
Migrate from browsermob to browserup proxy

### LINKED ISSUE #1019: Consider migrating to browserup proxy
## Details
https://github.com/browserup/browserup-proxy

### PR DESCRIPTION
**Pull request by rosolko**
## Notes
Closes #1019 
Linked with https://github.com/browserup/browserup-proxy/issues/199

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome_headless firefox_headless` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by asolntsev** [comment]
@rosolko Looks good. Do you have any ideas why the build is failing?

**Comment by rosolko** [comment]
@asolntsev unfortunately, no :(

**Comment by asolntsev** [comment]
@rosolko See commit [dd395dfb](https://github.com/selenide/selenide/commit/dd395dfba59e02b29c0cc95dc5f31ce359941473) - it fixed the problem.

**Comment by rosolko** [comment]
@asolntsev Good catch!

**Pull request merged**
