### PR TITLE
Upgrade to selenium4 alpha7

### PR DESCRIPTION
**Pull request by asolntsev**
## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome_headless firefox_headless` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by asolntsev** [comment]
Current status: 
1. We have upgraded Selenide code to Selenium 4.apha5 in this PR.
2. Almost all tests are green except one.
3. This one test wait for https://github.com/SeleniumHQ/selenium/issues/8346 - I cannot figure out any other way to fix this test. :(

**Comment by asolntsev** [comment]
Well, the PR is green now. Once Selenium 4.0 is released, we are ready for upgrade.

**Comment by BorisOsipov** [comment]
Updated to alpha7. Submit an issue https://github.com/SeleniumHQ/selenium/issues/8860

**Comment by asolntsev** [comment]
I have created another PR for upgrading to selenium-java:4.0.0-beta-1:  https://github.com/selenide/selenide/pull/1407

**Comment by BorisOsipov** [comment]
>I have created another PR for upgrading to selenium-java:4.0.0-beta-1: #1407

lets close this one then?

**Comment by asolntsev** [comment]
Yes, let's close it

**Pull request closed without merging**
