### PR TITLE
#1453 added no side effect soft assertion

### PR DESCRIPTION
**Pull request by evpl**
From #1453

This is a no side effects (in multithreading) and user-obvious way to invoke soft assertions in tests.

## Proposed changes
- added `com.codeborne.selenide.softassertion` package
- added `com.codeborne.selenide.softassertion.SoftAssertion` interface
- added `com.codeborne.selenide.softassertion.SoftAssertionByAssertionMode` implementation
- added `withSoftAssertionMode(Runnable)` and `withSoftAssertionMode(Supplier)` methods to `com.codeborne.selenide.Selenide`

## Checklist
- [ ] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by evpl** [comment]
@asolntsev
I haven't added tests yet. I am interested in your opinion on this concept. If everything goes well, I will finalize this request.

**Comment by evpl** [comment]
I realized that soft assertion on single element / collection doesn't make sense. I left only general soft assertion.

**Comment by evpl** [comment]
@asolntsev Now I see that this is not easy to do. Too many changes. Maybe I'll continue much later :(

**Comment by asolntsev** [comment]
@evpl Sorry, I haven't looked at your PR yet. 
No problems, we can discuss it at any moment.

**Pull request closed without merging**
