### PR TITLE
#1254 add methods to mock any server response in Selenide proxy

### PR DESCRIPTION
**Pull request by asolntsev**
Finally, implementation of #1254

### CODE REVIEW

**Review by BorisOsipov — APPROVED** [review]

**Comment by arturshevchenko** [comment]
idk why but this does not work. 

here is my test just like iin example:
```
    @Test
    public void test() throws InterruptedException {
        Configuration.proxyEnabled = true;
        Configuration.browserVersion = "120";
        open();
        getSelenideProxy().responseMocker().mockText("cik-mock",
                urlEquals(RequestMatcher.HttpMethod.POST, "https://api.demoblaze.com/view"),
                () -> "{price: 9999}"
        );
        open("https://www.demoblaze.com/prod.html?idp_=1");
        getSelenideProxy().responseMocker().resetAll();

        Thread.sleep(Duration.ofSeconds(10L));
    }
```

attachment of video:
https://github.com/selenide/selenide/assets/46380626/0759962d-467b-4cc3-965a-2da2725c0d7b

**Comment by arturshevchenko** [comment]
> @arturshevchenko Exactly the same code works on my machine. But I see from your video that SLF4J is not configured in your project. Please setup slf4j, and you will see the error details in logs. See https://www.youtube.com/watch?v=4Kh5yppP8zY&ab_channel=DEVCLUB.EU&t=9m22s

strange. on ,mmy in gives thats error logs: 
`23:59:07.813 [LittleProxy-0-ClientToProxyWorker-0] ERROR org.littleshoot.proxy.impl.ClientToProxyConnection - (AWAITING_INITIAL) [id: 0x92d77c94, L:/192.168.1.14:56534 - R:/192.168.1.14:56544]: Caught an exception on ClientToProxyConnection
java.lang.NoSuchMethodError: 'java.lang.String io.netty.handler.codec.http.HttpRequest.uri()'
	at com.browserup.bup.filters.HttpsOriginalHostCaptureFilter.<init>(HttpsOriginalHostCaptureFilter.java:29) ~[browserup-proxy-core-2.2.16.jar:?]
	at com.browserup.bup.BrowserUpProxyServer$7.filterRequest(BrowserUpProxyServer.java:1456) ~[browserup-proxy-core-2.2.16.jar:?]
	at com.browserup.bup.filters.BrowserUpHttpFilterChain.lambda$new$0(BrowserUpHttpFilterChain.java:45) ~[browserup-proxy-core-2.2.16.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.browserup.bup.filters.BrowserUpHttpFilterChain.<init>(BrowserUpHttpFilterChain.java:46) ~[browserup-proxy-core-2.2.16.jar:?]
	at com.browserup.bup.BrowserUpProxyServer$1.filterRequest(BrowserUpProxyServer.java:339) ~[browserup-proxy-core-2.2.16.jar:?]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.doReadHTTPInitial(ClientToProxyConnection.java:234) ~[littleproxy-1.1.0-beta-bmp-17.jar:?]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:206) ~[littleproxy-1.1.0-beta-bmp-17.jar:?]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:80) ~[littleproxy-1.1.0-beta-bmp-17.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection.readHTTP(ProxyConnection.java:135) ~[littleproxy-1.1.0-beta-bmp-17.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection.read(ProxyConnection.java:120) ~[littleproxy-1.1.0-beta-bmp-17.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection.channelRead0(ProxyConnection.java:587) ~[littleproxy-1.1.0-beta-bmp-17.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at org.littleshoot.proxy.impl.ProxyConnection$RequestReadMonitor.channelRead(ProxyConnection.java:715) ~[littleproxy-1.1.0-beta-bmp-17.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at org.littleshoot.proxy.impl.ProxyConnection$BytesReadMonitor.channelRead(ProxyConnection.java:692) ~[littleproxy-1.1.0-beta-bmp-17.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1302) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) ~[netty-all-4.0.51.Final.jar:4.0.51.Final]
	at java.lang.Thread.run(Thread.java:1583) [?:?]`

**Comment by asolntsev** [comment]
Oh yes, now we see the cause:
> java.lang.NoSuchMethodError: 'java.lang.String io.netty.handler.codec.http.HttpRequest.uri()'

This is the same problem with dependencies as described here: https://selenide.org/2020/11/17/why-proxy-does-not-work-in-selenoid/

and here: https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html

**Comment by arturshevchenko** [comment]
@asolntsev after fixing all dependencies -- mock is gone at all :D i left only selenid, selenide proxy,  slf4j and testng. run this test and nothein happens.

```
    @Test
    public void test() throws InterruptedException {
        Configuration.proxyEnabled = true;

        String jsonToReplace = "{\"cat\": \"phone\", \"id\": 1, \"price\": 999.0,\"title\": \"LOLA s6\"}";

        open();
        getSelenideProxy().responseMocker().mockText("test_replace",
                urlEndsWith(POST, "api.demoblaze.com/view"),
                () -> jsonToReplace

        );
        open("https://www.demoblaze.com/prod.html?idp_=1");

        getSelenideProxy().responseMocker().resetAll();

        Thread.sleep(Duration.ofSeconds(5L));
    }
```

but when i use native way of selenium all works fins

```
    @Test
    void selenium() throws InterruptedException {
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("disable-web-security");
        Configuration.browserCapabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);

        String jsonToReplace = "{\"cat\": \"phone\", \"id\": 1, \"price\": 999.0,\"title\": \"LOLA s6\"}";

        open();

        WebDriver driver = WebDriverRunner.getWebDriver();
        NetworkInterceptor interceptor = new NetworkInterceptor(driver,
                Route.matching(req -> req.getUri().contains("/api.demoblaze.com/view")).to(
                        () -> req -> new HttpResponse()
                                .setStatus(200)
                                .addHeader("Content-Type", "application/json")
                                .setContent(Contents.utf8String(jsonToReplace))
                )
        );

        open("https://www.demoblaze.com/prod.html?idp_=1");

        Thread.sleep(Duration.ofSeconds(10L));
        interceptor.close();
    }
```

**Comment by BorisOsipov** [comment]
> .addHeader("Content-Type", "application/json")

Obviously this is the cause of your problem.

**Comment by asolntsev** [comment]
Yes, the problem is that Selenide mocker doesn't add http header `"Content-Type": "application/json"`. 
We should add it.

**Comment by arturshevchenko** [comment]
@BorisOsipov is it possible to add header using selenide mocker?

**Comment by arturshevchenko** [comment]
@asolntsev is this feature request for selenide? or is it known way how to add header with selenide?

**Comment by asolntsev** [comment]
@arturshevchenko Yes, it's a feature request for sure. :)

**Comment by arturshevchenko** [comment]
will be waiting for implementation ❤️

**Comment by asolntsev** [comment]
@arturshevchenko Registered a feature request: https://github.com/selenide/selenide/issues/2705

**Pull request merged**
