### PR TITLE
add parent element to ElementFinder.getSearchCriteria

### PR DESCRIPTION
**Pull request by petroOv-PDFfiller**
## Proposed changes
In https://github.com/selenide/selenide/issues/61 i saw message about error format https://github.com/selenide/selenide/issues/61#issuecomment-642647647
but it format is not apply when we use element chain 
Example: $("div").$(".someClass").$("div")
if the latest element is not found  - we take message: Element not found {div}
Now it will checks and put all parent paths like as it works for ElementsCollection
## Checklist
- [x] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by asolntsev** [comment]
@petroOv-PDFfiller  Please fix the test.

**Comment by petroOv-PDFfiller** [comment]
> @petroOv-PDFfiller Please fix the test.

local run is ok, where i can find travis build report?

**Comment by petroOv-PDFfiller** [comment]
> @petroOv-PDFfiller Please fix the test.

found, working on fixes

**Review by asolntsev — APPROVED** [review]

**Comment by asolntsev** [comment]
@petroOv-PDFfiller Thank you for the PR!
Merged, will be released in Selenide 5.16.0 soon.

**Pull request merged**
