### PR TITLE
Fix Or and And conditions logic: empty list in ctor not allowed, PECS in ctor

### PR DESCRIPTION
**Pull request by evpl**
## Proposed changes
- fixed logic for `com.codeborne.selenide.conditions.Or`, `com.codeborne.selenide.conditions.And`
- added tests to `com.codeborne.selenide.conditions.OrTest`,  `com.codeborne.selenide.conditions.AndTest`
- added info to `CHANGELOG.md`

## Checklist
- [x] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by evpl** [comment]
@asolntsev pls review

**Comment by BorisOsipov** [comment]
@evpl FMPOV 
`$().shouldNot(new And("fo
", java.util.Collections.emptyList()));

**Comment by BorisOsipov** [comment]
@evpl FMPOV
`$().shouldNot(new And\Or("foo", emptyList()));` and `$().should(new And\Or("foo", emptyList()));` must always fail test. It is mistake in autotest and we should not allow such cases.
If someone need such things, it have to write explicitly its intend like 
```
if(conditionList.isEmpty()) {
 donothing()
}
else {
 $().shouldNot(new And\Or("foo", conditionList()));
}
```

**Comment by BorisOsipov** [comment]
closed by missclick. sorry.

**Comment by evpl** [comment]
@BorisOsipov do you mean IllegalArgumentException in constructor?

**Comment by asolntsev** [comment]
@evpl I agree, empty conditions list should be forbidden.
Yes, IllegalArgumentException in `Or` and `And` constructor is reasonable.

**Comment by BorisOsipov** [comment]
@evpl yep

**Comment by evpl** [comment]
@BorisOsipov @asolntsev ok, i'll fix it in this PR

**Comment by evpl** [comment]
@BorisOsipov @asolntsev done

**Review by asolntsev — APPROVED** [review]

**Pull request merged**
