### PR TITLE
#2769 add method `$.scroll()` with direction and length parameters

### PR DESCRIPTION
**Pull request by donnieHub**
## Proposed changes
Quite often there is a need to scroll down a particular element on a page (for example left menu on youtube page). This can be useful when content inside the element appears dynamically, i.e. only when you scroll down to it.
Less often there is a need to scroll an element to the right.

## Checklist
- [x] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by otter1990** [comment]
Add somebody method `scrollToCenter` please :)

My entire project is riddled with `.scrollIntoView("{block: 'center'}")` methods

**Comment by asolntsev** [comment]
> Someone add method `scrollToCenter()` please :)

@otter1990 Why don't you add this method? This is open source, your contribution is welcome! ;)

**Review by asolntsev — CHANGES_REQUESTED** [review]
@donnieHub Thank you for the contribution!
Overall, it's a useful feature.

Few nuances:
1. Are you sure the name "Scroll on element" is clear for all people? Maybe it's better to call it like JavaScript function: `$.scrollTo()`? It's also not very clear, but at least such a function already exists in JavaScript, so it will be consistent. 
2. Instead of having two overloaded methods `scrollOnElement`, I suggest adding ONE method with parameter object `ScrollOptions`. Similar to `ClickOptions`, `DownloadOptions`, `TypeOptions`. It will let us easily add more parameters in future.

**Comment by asolntsev** [comment]
> Someone add method `scrollToCenter()` please :)
> My entire project is riddled with `.scrollIntoView("{block: 'center'}")` methods

@otter1990 Why don't you use the old good method `$.scrollTo()`?

**Comment by otter1990** [comment]
> @otter1990 Why don't you use the old good method `$.scrollTo()`?

I write tests for web mobile. scrollTo() method scrolls in such a way that the element ends up at the very top of the screen and is covered by the top menu of the site. If I use scrollIntoView(false), the element is hidden by the footer of the site. Therefore, I have to use scrollIntoView("{block: 'center'}")

**Comment by asolntsev** [comment]
@otter1990 Thank you! 
I was thinking that probably we just need to change behaviour of `scrollTo()` method? Let it scroll the element to the center of screen instead of top.

**Comment by otter1990** [comment]
> @otter1990 Thank you! I was thinking that probably we just need to change behaviour of `scrollTo()` method? Let it scroll the element to the center of screen instead of top.

May be. Personally, I wouldn't mind :)

**Comment by asolntsev** [comment]
> Someone add method `scrollToCenter()` please :)

@otter1990 Method `scrollToCenter()` has been added in Selenide 7.6.0.
See https://github.com/selenide/selenide/pull/2842

**Review by asolntsev — CHANGES_REQUESTED** [review]

**Review by asolntsev — APPROVED** [review]

**Pull request merged**
