### PR TITLE
#2130 oneOfTexts() - like conditions

### PR DESCRIPTION
**Pull request by Achitheus**
Hi everybody!

## Proposed changes
#2130

1. Four conditions added:
    - oneOfTexts(Collection\<String>)
    - oneOfTextsCaseSensitive(Collection\<String>)
    - oneOfExactTexts(Collection\<String>)
    - oneOfExactTextsCaseSensitive(Collection\<String>)
1. Unit tests added.

1. CHANGELOG.md is updated (but I'm not sure I did that correctly).

Feel free to ask questions and suggest corrections!

## Checklist
- [x] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command 
(my comment: `gradle check` fails with checkstyle errors because of LF/CRLF, but git must be fixed it while commiting/pushing)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Review by asolntsev — APPROVED** [review]

**Comment by asolntsev** [comment]
@Achitheus I already merged the pull request, but then started thinking :)

I have a question: why do you pass expected text as a collection?
 It makes my tests longer because I have to write `List.of`:
```java
$("#upper-case").shouldHave(oneOfTexts(List.of("foo", "this is sparta!", "bar")));
```

If we passed the expected texts as varargs, the test would be shorter (without `List.of`):
```java
$("#upper-case").shouldHave(oneOfTexts("foo", "this is sparta!", "bar"));
```

**Comment by Achitheus** [comment]
> @Achitheus I already merged the pull request, but then started thinking :)
> 
> I have a question: why do you pass expected text as a collection? It makes my tests longer because I have to write `List.of`:
> 
> ```java
> $("#upper-case").shouldHave(oneOfTexts(List.of("foo", "this is sparta!", "bar")));
> ```
> 
> If we passed the expected texts as varargs, the test would be shorter (without `List.of`):
> 
> ```java
> $("#upper-case").shouldHave(oneOfTexts("foo", "this is sparta!", "bar"));
> ```

Do you mean it makes *writing* tests longer?

To be honest I dont see an objectively correct answer to the question, that could satisfy all users. Looks like we need another overloaded method :D
I was thinking about cases with data providers via MethodSource. 
If we take Collection approach and for some reason we have an array we should do the following:
`$.shouldHave(oneOfTexts(Arrays.toList(targetArray)));`
If we want to do it in your way and there is a List for some reason then:
`$.shouldHave(oneOfTexts(targetList.toArray(new String[0])));`
I dont like both conversion processes :)

I see two main questions here
1. *What* users prefer to pass from data providers?
2. How often they write asserts just “by hand”, as in your example, when “hard-coded” strings are used?

I don't have enough experience to answer these questions, so I prefer to leave the solution to you or ask the community.  
Sir :)

**Comment by asolntsev** [comment]
@Achitheus Almost always, I personally write asserts "just by hand", and I believe this is the right way to write asserts. All kinds of data providers, factories, excels etc. bring complexity to the tests without a real need. Complexity should be avoided. 

If somebody pass data from MethodSource, they can return Array as easily as List. That's why I prefer array to list.

**Comment by asolntsev** [comment]
I created a follow-up PR: https://github.com/selenide/selenide/pull/2568

**Pull request merged**
