### PR TITLE
Added link to the correct dependency module (core)

### PR DESCRIPTION
**Pull request by vinogradoff**
You need to add browserup-proxy-core, not browserup-proxy dependency, so this link could be helpful to find the right dependency faster.

### CODE REVIEW

**Comment by vinogradoff** [comment]
stylecheck fix

**Review by asolntsev — APPROVED** [review]
The change is not bad, but it doesn't really solve the problem.
If one doesn't understand clause "add a dependency", he will also not understand the URL as well.

**Comment by vinogradoff** [comment]
@asolntsev it was from my experience, I've read the old message, googled for browserupproxy, added dependecy to browserup-proxy. Didn't work:-). Googled in Selenide project- and recalled it must be not browserup-proxy, but browserup-proxy-core. 

So new message would save me time to get to -core immediately.

**Comment by asolntsev** [comment]
@vinogradoff Probably it might be link to wiki post like https://github.com/selenide/selenide/wiki/Lazy-loading ?

**Comment by vinogradoff** [comment]
@asolntsev yes, actually the best would be 1) create the wiki article about Selenide Proxy 2) link it at a few spot like this one.

this was a quick-fix, I create an issue reminder for wiki.

**Pull request merged**
